
name: 🐛 报 BUG（Bug Report）
description: 报告一个可复现的BUG帮助我们修复框架（Report a bug to help us reproduce and fix it）
labels: [type/bug, status/new-issue]

body:
- type: markdown
  attributes:
    value: >
      #### 在向Paddle报bug之前，请先查询[历史issue](https://github.com/Ligoml/YOLO_paddle/issues)是否报过同样的bug。
      Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/Ligoml/YOLO_paddle/issues).

- type: textarea
  id: environment
  attributes:
    label: bug复现环境（bug reproduction environment）
    description: |
      请提供bug复现环境。
      Please provide bug reproduction environment.
  validations:
    required: true
    
- type: textarea
  id: code
  attributes:
    label: bug复现步骤及最小代码集（Bug reproduction steps and minimal code set）
    description:  |
      请提供bug复现步骤及最小代码集。 
      Please provide a clear and concise description of what the bug is.

      If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports, etc. For example:

      ```python
      # All necessary imports at the beginning
      import torch

      # A succinct reproducing example trimmed down to the essential parts:
      t = torch.rand(5, 10)  # Note: the bug is here, we should pass requires_grad=True
      t.sum().backward()
      ```

      If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com.

      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.

      ```python
      # Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ```
  validations:
    required: true
    
- type: textarea
  id: Desired-result
  attributes:
    label: 期望结果（Desired result）
    description: |
      请简要描述期望结果。
      Please briefly describe the expected output.
  validations:
    required: true
    
    
- type: textarea
  id: actual-result
  attributes:
    label: 实际结果（actual result）
    description: |
      请展示实际结果，并描述区别。
      Please show actual results and describe the difference.
  validations:
    required: true
    
- type: textarea
  id: others
  attributes:
    label: 其他补充   
  validations:
    required: false
    
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
