
name: 🐛 报 BUG（Bug Report）
description: 报告一个可复现的BUG帮助我们修复框架（Report a bug to help us reproduce and fix it）
labels: [type/bug, status/new-issue]

body:
- type: markdown
  attributes:
    value: >
      #### 在向Paddle报bug之前，请先查询[历史issue](https://github.com/Ligoml/YOLO_paddle/issues)是否报过同样的bug。
      
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/Ligoml/YOLO_paddle/issues).

- type: textarea
  id: code
  attributes:
    label: bug描述（Describe the Bug）
    description:  |
      请提供bug复现环境、bug复现步骤及最小代码集。 
      请清晰简洁的描述这个bug，最好附上bug复现环境、bug复现步骤及最小代码集，以便我们可以通过运行代码来重现错误。代码片段需要尽可能简洁，请花些时间去掉不相关的代码以帮助我们有效地调试。我们希望通过复制代码并运行得到与你相同的结果，请避免任何外部数据或包含相关的导入等。例如：
      ```python
      # 导入所有必要的库
      # paddlepaddle <= 2.1.2, gpu version
      import paddle

      # 一个简洁的片段，能够定位到bug
      a = paddle.rand(shape=[1,4])
      b = paddle.rand(shape=[1,4])
      a.stop_gradient = False
      b.stop_gradient = False
      
      c = paddle.zeros((4, 4))
      c[0, :] = a/b
      
      print('Is c requires grad: ', not c.stop_gradient) # 注意：这里出现了bug，期望 requires_grad=True
      ```
      如果代码太长，请将可执行代码放到[AIStudio](https://aistudio.baidu.com/aistudio/index)中并将项目设置为公开，请在项目中描述清楚bug复现步骤，在issue中描述期望结果与实际结果。
      
      Please provide a clear and concise description of what the bug is.
      If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports, etc. For example:
      ```python
      # All necessary imports at the beginning
      # paddlepaddle <= 2.1.2, gpu version
      import paddle

      # A succinct reproducing example trimmed down to the essential parts
      a = paddle.rand(shape=[1,4])
      b = paddle.rand(shape=[1,4])
      a.stop_gradient = False
      b.stop_gradient = False
      
      c = paddle.zeros((4, 4))
      c[0, :] = a/b
      
      print('Is c requires grad: ', not c.stop_gradient) # Note: the bug is here, expect requires_grad=True
      ```
      If the code is too long (hopefully, it isn't), please put the executable code in [AIStudio](https://aistudio.baidu.com/aistudio/index?lang=en) and set the project as public, please describe the bug reproduction steps clearly in the project, and describe the expected results & the results you observe in the issue.
      
      placeholder: |
      A clear and concise description of what the bug is.

      ```python
      # Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ```
  validations:
    required: true
    
- type: textarea
  id: Desired-result
  attributes:
    label: 期望结果（Desired result）
    description: |
      请简要描述期望结果。
      Please briefly describe the expected output.
  validations:
    required: true
    
    
- type: textarea
  id: actual-result
  attributes:
    label: 实际结果（actual result）
    description: |
      请展示实际结果，并描述区别。
      Please show actual results and describe the difference.
  validations:
    required: true
    
- type: markdown
  attributes:
    value: >
      感谢你的贡献 🎉！
      
      Thanks for your contribution 🎉!
