name: 🚀 新需求（Feature Request）
description: 提交一个你对Paddle的新需求（Submit a request for a new Paddle feature）
labels: [type/feature-request, status/new-issue]

body:
- type: markdown
  attributes:
    value: >
      #### 你可以在这里提出你对Paddle框架的新需求，包括但不限于：功能或模型缺失、功能不全或无法使用、精度/性能不符合预期等。
      
      #### You could submit a request for a new Paddle feature here, including but not limited to: new features or models, incomplete or unusable features, accuracy/performance not as expected, etc.

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
      
- type: textarea
  id: description
  attributes:
    label: 需求描述（Feature Description）
    description: |
      请尽可能包含需求场景、功能描述、使用频次等信息，全面的信息有利于我们准确评估你的需求。
      Please include as much information as possible, such as demand scenarios, function descriptions, and usage frequency. Comprehensive information will help us accurately assess your feature request.
    value: "任务目标（请描述您正在做的项目是什么，如模型、论文、项目是什么？）：/n 需求场景（请描述您的项目中为什么需要用此功能）：/n 功能描述（请简单描述或设计这个功能）：/n"
  validations:
    required: true
    
- type: textarea
  id: alternatives
  attributes:
    label: 替代实现（Alternatives）
    description: |
      请描述下你考虑过的任何替代解决方案或功能（如果有）。
      A description of any alternative solutions or features you've considered, if any.
  validations:
    required: false
    
- type: markdown
  attributes:
    value: >
      感谢你的贡献 🎉！
      
      Thanks for your contribution 🎉!
