name: 🚀 新需求（Feature Request）
description: 提交一个你对paddle的新需求（Submit a request for a new Paddle feature）
labels: [type/feature-request, status/new-issue]

body:
- type: markdown
  attributes:
    value: >
      #### 提出你对paddle的新需求
      
      #### Submit a request for a new Paddle feature

- type: textarea
  id: description
  attributes:
    label: 需求描述（Feature Description）
    description: |
      请尽可能包含需求场景、功能描述、使用频次等信息，全面的信息有利于我们准确评估你的需求。
      Please include as much information as possible, such as demand scenarios, function descriptions, and usage frequency. Comprehensive information will help us accurately assess your feature request.
  validations:
    required: true
    
- type: textarea
  id: alternatives
  attributes:
    label: 替代实现（Alternatives）
    description: |
      描述下你考虑过的任何替代解决方案或功能（如果有）。
      A description of any alternative solutions or features you've considered, if any.
  validations:
    required: false
    
- type: markdown
  attributes:
    value: >
      感谢你的贡献 🎉！
      
      Thanks for your contribution 🎉!
