

- type: textarea
  id: code2
  attributes:
    label: 相关代码
    description: |
      请附上aistudio项目地址 或 直接贴示例代码
  validations:
    required: true



- type: markdown
  attributes:
    value: >
      感谢你的贡献 🎉！Thanks for your contributio
